POST http://localhost:3332/videos
Content-Type: application/json

{
  "title": "Video node",
  "description": "this is the first video",
  "duration": 188
}

###

### use ?search=yourSearchName for search example GET http://localhost:3332/videos?search=node

GET http://localhost:3332/videos

###

PUT http://localhost:3332/videos/36adc50a-10a7-47d1-ac0a-18e31f8c0e9d
Content-Type: application/json

{
  "title": "Video node",
  "description": "this is the first video",
  "duration": 188
}

###

DELETE http://localhost:3332/videos/999865ac-0877-4a93-865a-f5b6fdd17e3e
